import './style.css'
import pb from './pocketbase.js'

//const authData = await pb.collection("users").authWithPassword('userFlightRadar@user.com', 'Fly12345');
const authData = await pb.collection("_superusers").authWithPassword('admin@admin.it', 'admin12345');

// after the above you can also access the auth data from the authStore
console.log(pb.authStore.isValid);
console.log(pb.authStore.token);
console.log(pb.authStore.record.id);

// create base collection
const base = await pb.collections.create({
    name: 'exampleBase',
    type: 'base',
    fields: [
        {
            name: 'title',
            type: 'text',
            required: true,
            min: 10,
        },
        {
            name: 'status',
            type: 'bool',
        },
    ],
});

// create auth collection
const auth = await pb.collections.create({
    name: 'exampleAuth',
    type: 'auth',
    createRule: 'id = @request.auth.id',
    updateRule: 'id = @request.auth.id',
    deleteRule: 'id = @request.auth.id',
    fields: [
        {
            name: 'name',
            type: 'text',
        }
    ],
    passwordAuth: {
        enabled: true,
        identityFields: ['email']
    },
});

// create view collection
const view = await pb.collections.create({
    name: 'exampleView',
    type: 'view',
    listRule: '@request.auth.id != ""',
    viewRule: null,
    // the schema will be autogenerated from the below query
    viewQuery: 'SELECT id, name from posts',
});